language: c
script:
  sudo make install
branches:
  only:
  - master
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
    - if [ ${TRAVIS_OS_NAME} = "linux" ]; then sudo add-apt-repository ppa:dns/gnu -y; sudo apt-get update -qq; sudo apt-get install -y autoconf automake m4 libtool doxygen liblua5.1-0-dev libdumbnet-dev; fi
    - if [ ${TRAVIS_OS_NAME} = "osx" ]; then brew update; brew install doxygen lua@5.1 libdnet; fi
install:  cd libnet && ../Prepare && ../Build
after_success:
    - bash <(curl -s https://codecov.io/bash)
#add email if you want to get notified
#notifications:
#  email:

