# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

dist: bionic

addons:
  apt:
    packages:
      - tree
      - doxygen
# homebrew:
#   packages:
#     - tree
#     - doxygen
#     - coreutils
#   update: true

before_install:
    - if [ ${TRAVIS_OS_NAME} = "osx" ]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install doxygen tree md5sha1sum; fi

script:
  - ./autogen.sh
  - ./configure --prefix=/ --disable-silent-rules
  - make doc
  - make release
  - make clean
  - make
  - make install-strip DESTDIR=/tmp/libnet
  - tree /tmp/libnet
